services:
  postgres-db:
    image: postgis/postgis:13-3.1
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    ports:
      # Expose the database port to your local machine on 5432
      - "5432:5432"
    restart: always

  mongo-db:
    image: mongo:5.0
    container_name: mongo_db
    volumes:
      - mongo_data:/data/db
    env_file: .env
    ports:
      # Expose the database port to your local machine on 27017
      - "27017:27017"
    restart: always

volumes:
  postgres_data:
  mongo_data: